### PR TITLE
Margrit/fix disco level

### LINKED ISSUE #83: Level 4: Player can only have a success if he is not infected

### LINKED ISSUE #85: Level 4: NPCs all spawn in one place -> lag
As is see this, currently the dancing NPCs in level 4 all spawn in a single spot, followed by an NPC explosion where they are distributed across the circle.

1. This causes some lag in my browser since a lot of collisions have to be computed.
2. Sometimes after the explosion almost all NPCs are infected, sometimes only one or two are.
   I think there is too much randomness here.

I suppose to spawn the NPCs more distributed across the circle.
And then have a certain chance for each NPC to spawn infected or not.

### PR DESCRIPTION
**Pull request by maccxs**
This is based on #90, so merge #90 first.
* The npcs are  placed randomly on the dancefloor not at the same position
* At the beginning three have the virus
* Adjusted the infection spread for this scenario (a little faster)
* The level can only be won if also the player has not been infected.

### CODE REVIEW

File: YouVsVirus/Assets/Scripts/leveldisco/CreatePopLeveldisco.cs [hunk 1]
```diff
@@ -98,18 +98,32 @@ private void PlaceHumans()
...
+                                        position,
                                         Quaternion.identity));
                 // give all npcs a unique id
                 NPCs[i - 1].myID = i - 1;
             }
-            //  Infect one.
+            //  Infect three.
             NPCs[33].SetInitialCondition(NPC.EXPOSED);
             NPCs[81].SetInitialCondition(NPC.INFECTIOUS);
+            NPCs[66].SetInitialCondition(NPC.EXPOSED);
```
Comment (holke) [inline YouVsVirus/Assets/Scripts/leveldisco/CreatePopLeveldisco.cs:126]: I am not a fan of magic numbers.
If we later change the number of NPCs to 70 or so, this will crash.

**Comment by holke** [comment]
Performance increased significantly, great.
The level got easier, since the spreads is now slower.
Was this indetended? I thought you liked the difficulty?
If so, i will merge this.

For later: In my opinion, if the level is lost when the player returns infected (which is a good change), then the level could also end as soon as the player gets infected.
Otherwise you get infected, fight another minute or so to get Jeff out, only to get the message then that you lost...a bit frustrating. Even more so if you know that you have lost now, but still have to walk to the exit to make the level end.

**Comment by maccxs** [comment]
Hi, I wanted the spread to be difficult but it's hard to get it done right. Please merge. This is only a small adjustment that we can try to set just right at a later point. The thing with the ending is also a good idea. I had that in mind at first, but it got lost in the end.
